# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "taskmapper-kanbanpad"
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["HybridGroup"]
  s.date = "2013-04-16"
  s.description = "Allows taskmapper to interact with kanbanpad."
  s.email = "sonia@hybridgroup.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rbenv-gemsets",
    ".rbenv-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/kanbanpad/kanbanpad-api.rb",
    "lib/provider/api-extensions.rb",
    "lib/provider/comment.rb",
    "lib/provider/kanbanpad.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/taskmapper-kanbanpad.rb",
    "spec/fixtures/comments.json",
    "spec/fixtures/comments/4ef2719bf17365000110df9e.json",
    "spec/fixtures/projects.json",
    "spec/fixtures/projects.xml",
    "spec/fixtures/projects/be74b643b64e3dc79aa0.json",
    "spec/fixtures/projects/be74b643b64e3dc79aa0.xml",
    "spec/fixtures/projects/create.json",
    "spec/fixtures/projects/create.xml",
    "spec/fixtures/projects/test.rb",
    "spec/fixtures/steps/4dc312f49bd0ff6c37000040.json",
    "spec/fixtures/tasks.json",
    "spec/fixtures/tasks.xml",
    "spec/fixtures/tasks/4cd428c496f0734eef000007.json",
    "spec/fixtures/tasks/4cd428c496f0734eef000007.xml",
    "spec/fixtures/tasks/4cd428c496f0734eef000008.json",
    "spec/fixtures/tasks/4cd428c496f0734eef000008.xml",
    "spec/fixtures/tasks/4dc31c4c9bd0ff6c3700004e.json",
    "spec/fixtures/tasks/create.xml",
    "spec/project_comments_spec.rb",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/ticket_comments_spec.rb",
    "spec/ticketmaster-kanbanpad_spec.rb",
    "spec/tickets_spec.rb",
    "taskmapper-kanbanpad.gemspec"
  ]
  s.homepage = "http://github.com/hybridgroup/taskmapper-kanbanpad"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "taskmapper Provider for Kanbanpad"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<taskmapper>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_development_dependency(%q<rcov>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<taskmapper>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<simplecov>, ["~> 0.5"])
      s.add_dependency(%q<rcov>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<taskmapper>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<simplecov>, ["~> 0.5"])
    s.add_dependency(%q<rcov>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

