# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ticketmaster-kanbanpad}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["HybridGroup"]
  s.date = %q{2010-11-23}
  s.description = %q{Allows ticketmaster to interact with kanbanpad.}
  s.email = %q{sonia@hybridgroup.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "VERSION",
    "lib/kanbanpad/kanbanpad-api.rb",
    "lib/provider/comment.rb",
    "lib/provider/kanbanpad.rb",
    "lib/provider/project.rb",
    "lib/provider/ticket.rb",
    "lib/ticketmaster-kanbanpad.rb",
    "rakefile",
    "spec/comments_spec.rb",
    "spec/fixtures/projects.xml",
    "spec/fixtures/projects/be74b643b64e3dc79aa0.xml",
    "spec/fixtures/projects/create.xml",
    "spec/fixtures/tasks.xml",
    "spec/fixtures/tasks/4cd428c496f0734eef000007.xml",
    "spec/fixtures/tasks/4cd428c496f0734eef000008.xml",
    "spec/fixtures/tasks/create.xml",
    "spec/projects_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/ticketmaster-kanbanpad_spec.rb",
    "spec/tickets_spec.rb",
    "ticketmaster-kanbanpad.gemspec"
  ]
  s.homepage = %q{http://github.com/hybridgroup/ticketmaster-kanbanpad}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ticketmaster Provider for Kanbanpad}
  s.test_files = [
    "spec/comments_spec.rb",
    "spec/projects_spec.rb",
    "spec/spec_helper.rb",
    "spec/ticketmaster-kanbanpad_spec.rb",
    "spec/tickets_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

